In [1]:
import os
import pickle

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

In [10]:
def load_pickles(folder_path):
    all_data = {} 

    for filename in os.listdir(folder_path):
        if filename.endswith('.pkl'):  # Check if the file is a pickle file
            file_path = os.path.join(folder_path, filename)
            with open(file_path, 'rb') as file:
                # Unpickle the file and store its contents in the dictionary
                data = pickle.load(file)
                all_data[filename] = data

    return all_data

# Replace 'your_folder_path' with the path to your folder containing the pickle files
folder_path = '_results_nfl'
unpickled_data = load_pickles(folder_path)

In [11]:
start_ind = 2551
end_ind = 2647

# Start and end time
start = '2023-06-28 00:00:00'
end = '2023-06-28 23:45:00'

# Frequency of the time stamps (e.g., 'H' for hourly)
freq = '15T'

# Creating the time stamp sequence
x = pd.date_range(start=start, end=end, freq=freq)

In [12]:
# unpickled_data['encoder_test_res.pkl']['preds'][0].squeeze().cpu()

fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=unpickled_data['transformer_nfl_test_res.pkl']['preds'][start_ind:end_ind, 0].squeeze().cpu(), mode='lines', name=f'Transformer'))
fig.add_trace(go.Scatter(x=x, y=unpickled_data['mlp_nfl_test_res.pkl']['preds'][0][start_ind:end_ind].squeeze().cpu(), mode='lines', name=f'MLP'))
fig.add_trace(go.Scatter(x=x, y=unpickled_data['xgboost_nfl_test_res.pkl']['preds'][0][start_ind:end_ind].squeeze(), mode='lines', name=f'XGBoost'))
fig.add_trace(go.Scatter(x=x, y=unpickled_data['encoder_test_res.pkl']['preds'][0][start_ind:end_ind].squeeze().cpu(), mode='lines', name=f'Encoder'))

fig.add_trace(go.Scatter(x=x, y=unpickled_data['encoder_test_res.pkl']['gt'][0][start_ind:end_ind].squeeze().cpu(), mode='lines', name='Ground Truth', line=dict(dash='dash', color='orange')))

# fig.add_trace(go.Scatter(x=x, y=unpickled_data['transformer_nfl_test_res.pkl']['preds'][start_ind:end_ind, 1].squeeze().cpu(), mode='lines', name=f'Transformer'))
# fig.add_trace(go.Scatter(x=x, y=unpickled_data['mlp_nfl_test_res.pkl']['preds'][1][start_ind:end_ind].squeeze().cpu(), mode='lines', name=f'MLP'))
# fig.add_trace(go.Scatter(x=x, y=unpickled_data['xgboost_nfl_test_res.pkl']['preds'][1][start_ind:end_ind].squeeze(), mode='lines', name=f'XGBoost'))
# fig.add_trace(go.Scatter(x=x, y=unpickled_data['encoder_test_res.pkl']['preds'][1][start_ind:end_ind].squeeze().cpu(), mode='lines', name=f'Encoder'))

# fig.add_trace(go.Scatter(x=x, y=unpickled_data['encoder_test_res.pkl']['gt'][1][start_ind:end_ind].squeeze().cpu(), mode='lines', name='Ground Truth', line=dict(dash='dash', color='orange')))

fig.update_layout(
    font=dict(size=32, family="Times New Roman"), 
    title=dict(x=0.5, y=0.96, text='System imbalance prediction', font=dict(size=50)),
    xaxis_title='Time (h)',
    yaxis_title='System imbalance (MW)',
    bargap=0.05, # small gap between bars for better visualization
    legend=dict(
        x=0.5,
        y=-0.25,  # You might need to adjust this value based on your specific figure
        xanchor='center',
        yanchor='top',
        orientation='h'  # Horizontal orientation
    ),
    margin=dict(l=20, r=20, t=100, b=20),   # Adjust bottom margin to ensure legend is visible
    plot_bgcolor='white',
    width=1983,  # Width as calculated for 4/5 of A4 paper width
    height=900,  # Example height, adjust as needed
)

# Customize x-axis and y-axis line properties
fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=True, tickfont=dict(size=32))
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', mirror=True, tickfont=dict(size=32))

# Show plot
fig.show(config={'staticPlot': True})
pio.write_image(fig, 'predicitons_nfl.pdf')

In [13]:
folder_path = '_results_fl'
unpickled_data = load_pickles(folder_path)

In [14]:
unpickled_data['tft_test_res.pkl']['y_true']

array([[ 221.701,   72.366,  234.895, ...,   12.685,  104.991,  -47.274],
       [  72.366,  234.895,    3.753, ...,  104.991,  -47.274,    2.17 ],
       [ 234.895,    3.753,   72.379, ...,  -47.274,    2.17 ,  -33.357],
       ...,
       [  18.474,   45.283,  -20.549, ...,  -33.795,  -43.184,   43.858],
       [  45.283,  -20.549,   51.421, ...,  -43.184,   43.858, -106.571],
       [ -20.549,   51.421,  -92.085, ...,   43.858, -106.571, -141.174]],
      dtype=float32)

In [15]:
unpickled_data['transformer_fl_test_res.pkl']['gt'].squeeze()

tensor([[ 221.7010,   72.3660,  234.8950,  ...,   12.6850,  104.9910,
          -47.2740],
        [  72.3660,  234.8950,    3.7530,  ...,  104.9910,  -47.2740,
            2.1700],
        [ 234.8950,    3.7530,   72.3790,  ...,  -47.2740,    2.1700,
          -33.3570],
        ...,
        [  -1.1690,   18.4740,   45.2830,  ...,  -92.0850,  -33.7950,
          -43.1840],
        [  18.4740,   45.2830,  -20.5490,  ...,  -33.7950,  -43.1840,
           43.8580],
        [  45.2830,  -20.5490,   51.4210,  ...,  -43.1840,   43.8580,
         -106.5710]])

In [16]:
unpickled_data['mlp_fl_test_res.pkl']['gt'][0].squeeze()

tensor([ 221.7010,   72.3660,  234.8950,  ...,   43.8580, -106.5710,
        -141.1740], device='cuda:0')

In [17]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=unpickled_data['transformer_fl_test_res.pkl']['preds'][start_ind:end_ind, 0].squeeze().cpu(), mode='lines', name=f'Transformer'))
fig.add_trace(go.Scatter(x=x, y=unpickled_data['mlp_fl_test_res.pkl']['preds'][0][start_ind:end_ind].squeeze().cpu(), mode='lines', name=f'MLP'))
fig.add_trace(go.Scatter(x=x, y=unpickled_data['xgboost_fl_test_res.pkl']['preds'][0][start_ind:end_ind].squeeze(), mode='lines', name=f'XGBoost'))
fig.add_trace(go.Scatter(x=x, y=unpickled_data['tft_test_res.pkl']['preds'][start_ind:end_ind,0], mode='lines', name=f'TFT', line=dict(color="maroon")))

fig.add_trace(go.Scatter(x=x, y=unpickled_data['mlp_fl_test_res.pkl']['gt'][0][start_ind:end_ind].squeeze().cpu(), mode='lines', name='Ground Truth', line=dict(dash='dash', color='orange')))

# fig.add_trace(go.Scatter(x=x, y=unpickled_data['transformer_fl_test_res.pkl']['preds'][start_ind:end_ind, 1].squeeze().cpu(), mode='lines', name=f'Transformer'))
# fig.add_trace(go.Scatter(x=x, y=unpickled_data['mlp_fl_test_res.pkl']['preds'][1][start_ind:end_ind].squeeze().cpu(), mode='lines', name=f'MLP'))
# fig.add_trace(go.Scatter(x=x, y=unpickled_data['xgboost_fl_test_res.pkl']['preds'][1][start_ind:end_ind].squeeze(), mode='lines', name=f'XGBoost'))

# fig.add_trace(go.Scatter(x=x, y=unpickled_data['mlp_fl_test_res.pkl']['gt'][1][start_ind:end_ind].squeeze().cpu(), mode='lines', name='Ground Truth', line=dict(dash='dash', color='orange')))

fig.update_layout(
    font=dict(size=32, family="Times New Roman"), 
    title=dict(x=0.5, y=0.96, text='System imbalance prediction', font=dict(size=50)),
    xaxis_title='Time (h)',
    yaxis_title='System imbalance (MW)',
    bargap=0.05, # small gap between bars for better visualization
    legend=dict(
        x=0.5,
        y=-0.25,  # You might need to adjust this value based on your specific figure
        xanchor='center',
        yanchor='top',
        orientation='h'  # Horizontal orientation
    ),
    margin=dict(l=20, r=20, t=100, b=20),   # Adjust bottom margin to ensure legend is visible
    plot_bgcolor='white',
    width=1983,  # Width as calculated for 4/5 of A4 paper width
    height=900,  # Example height, adjust as needed
)

# Customize x-axis and y-axis line properties
fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=True, tickfont=dict(size=32))
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', mirror=True, tickfont=dict(size=32))

# Show plot
fig.show(config={'staticPlot': True})
pio.write_image(fig, 'predicitons_fl.pdf')

In [9]:
unpickled_data['transformer_nfl_test_res.pkl']['preds'][:, 0].squeeze().cpu().max()

tensor(107.6693)

In [10]:
unpickled_data['transformer_nfl_test_res.pkl']['preds'][:, 0].squeeze().cpu().min()

tensor(-131.7134)

In [14]:
unpickled_data.keys()

dict_keys(['mlp_fl_test_res.pkl', 'transformer_fl_test_res.pkl', 'xgboost_fl_test_res.pkl'])